# Generated by Django 4.2 on 2023-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carusel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
